spring:
  application:
    name: cloudthread-spring-cloud-config-starter-example
  config:
    import: "configserver:http://localhost:8888"
cloudthread:
  bootstrap:
    enable: true
    thread-pool:
      core-size: 5
      max-size: 10
      queue-capacity: 50