{
 "title": "Cloud Dynamic Thread Pool Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application_name", "query": "label_values(application_name)" },
   {
    "name": "dynamic_thread_pool_id",
    "query": "label_values(dynamic_thread_pool_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Core Threads",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dynamic_thread_pool_core_size{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maximum Threads",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "dynamic_thread_pool_maximum_size{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "dynamic_thread_pool_current_size{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "dynamic_thread_pool_active_size{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "dynamic_thread_pool_queue_remaining_capacity{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "dynamic_thread_pool_queue_size{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rejected Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "dynamic_thread_pool_reject_count{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "dynamic_thread_pool_completed_task_count{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}