global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cloudthread-spring-cloud-config-starter-example'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:18080']